# docker-Specify the compose version
version: "3"

services:
  app:
    build: .
    tty: true
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./app/app:/app/app
      - ./app/config:/app/config
      - ./app/hooks:/app/hooks
      - ./app/i18n:/app/i18n
      - ./app/public:/app/public
      - ./app/service:/app/service
      - ./app/types:/app/types
      - ./app/utils:/app/utils
      - ./app/.editorconfig:/app/.editorconfig
      - ./app/.eslintrc.json:/app/.eslintrc.json
      - ./app/.gitignore:/app/.gitignore
      - ./app/next.config.js:/app/next.config.js
      - ./app/package.json:/app/package.json
      - ./app/postcss.config.js:/app/postcss.config.js
      - ./app/tailwind.config.js:/app/tailwind.config.js
      - ./app/tsconfig.json:/app/tsconfig.json
      - ./app/typography.js:/app/typography.js
      - ./app/start-app.sh:/app/start-app.sh

    # volumes:
    #   - ./app:/app